version: '3'

services:
  parse_back:
    container_name: service_parse_back
    build:
      context: ./parse_back # Directory built image
      dockerfile: Dockerfile
    ports:
      - "8000:8000" # host 8000 -> container 8000
    volumes:
      - ./parse_back/app:/code/app # app -> container -> /code/app automatic mapping (auto reload)
    environment:
      - POETRY_VIRTUALENVS_CREATE=false # Poetry doesn't make virtualenv...
    command: ["poetry", "run", "gunicorn", "app.main:app", "--workers", "4", "--worker-class", "uvicorn.workers.UvicornWorker", "--bind", "0.0.0.0:8000"]
    working_dir: /code
    networks:
      - app-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]  
  web_app:
    container_name: service_web_app
    build:
      context: ./web_app
      dockerfile: Dockerfile
    ports:
      - "10020:10020"
    networks:
      - app-network

    
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/fullchain.pem:/etc/nginx/ssl/fullchain.pem
      - ./nginx/privkey.pem:/etc/nginx/ssl/privkey.pem
    depends_on:
      - parse_back
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  app: