version: '3'

services:
  parse_back:
    build:
      context: ./parse_back # Directory built image
      dockerfile: Dockerfile
    ports:
      - "8000:8000" # host 8000 -> container 8000
    volumes:
      - ./parse_back/app:/code/app # app -> container -> /code/app automatic mapping (auto reload)
    environment:
      - POETRY_VIRTUALENVS_CREATE=false # Poetry doesn't make virtualenv...
    command: ["poetry", "run", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--root-path", "/api/v1"]
    working_dir: /code
    networks:
      - app-network
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/fullchain.pem:/etc/nginx/ssl/fullchain.pem
      - ./nginx/privkey.pem:/etc/nginx/ssl/privkey.pem
    depends_on:
      - parse_back
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  app: